Add enabled/disabled check for external services
open-commercial/sic-api pull request #461
Opened 2023-03-14 20:48 UTC by belluccifranco

#456

2023-03-14 20:49 UTC, belluccifranco commented
NO olvidar actualizar las variables de entorno

2023-03-16 17:27 UTC, k31kur0n0 requested changes

2023-03-16 17:27 UTC, k31kur0n0 commented on src/main/java/sic/service/impl/CloudinaryImageUploaderServiceImpl.java
>    public void isUrlValida(String url) {
Quedo sin uso este método

2023-03-17 18:02 UTC, k31kur0n0 approved these changes

2023-03-17 19:16 UTC, k31kur0n0 requested changes

2023-03-31 20:23 UTC, k31kur0n0 requested changes
Add feature flag for Cloudinary, MercadoPago and Gmail services.

2023-04-15 14:29 UTC, k31kur0n0 approved these changes

2023-05-22 12:03 UTC, k31kur0n0 approved these changes

2023-06-02 20:40 UTC, merged